server:
  port: 8080

spring:
  application:
    name: electronic-bazaar-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://electronic-bazaar-product-service:8081
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://electronic-bazaar-auth-service:8082
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: http://electronic-bazaar-customer-service:8083
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://electronic-bazaar-order-service:8084
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: http://electronic-bazaar-payment-service:8085
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
          

jwt:
  secret: ${JWT_SECRET:replace_this_with_a_very_long_secret}
