# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql
# spec:
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - name: mysql
#           image: mysql:8.0
#           env:
#             - name: MYSQL_DATABASE
#               value: "electronic_bazaar"
#             - name: MYSQL_USER
#               value: "eb_user"
#             - name: MYSQL_PASSWORD
#               value: "eb_pass"
#             - name: MYSQL_ROOT_PASSWORD
#               value: "root"
#           ports:
#             - containerPort: 3306
#           volumeMounts:
#             - name: mysql-pvc
#               mountPath: /var/lib/mysql
#       volumes:
#         - name: mysql-pvc
#           emptyDir: { }
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
# spec:
#   ports:
#     - port: 3306
#       targetPort: 3306
#   selector:
#     app: mysql
#   type: ClusterIP
