apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronic-bazaar-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electronic-bazaar-order
  template:
    metadata:
      labels:
        app: electronic-bazaar-order
    spec:
      containers:
        - name: electronic-bazaar-order
          image: shubhamnamdev01/electronic-bazaar-order-service:v1
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/electronic_bazaar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: JWT_SECRET
              value: replace_this_with_a_very_long_secret
            - name: PRODUCT_SERVICE_URL
              value: http://electronic-bazaar-product-service:8081
            - name: CUSTOMER_SERVICE_URL
              value: http://electronic-bazaar-customer-service:8083
---
apiVersion: v1
kind: Service
metadata:
  name: electronic-bazaar-order-service
spec:
  selector:
    app: electronic-bazaar-order
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
