spring:
  application:
    name: electronic-bazaar-product-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/electronic_bazaar?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:product_user}
    password: ${SPRING_DATASOURCE_PASSWORD:product_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:replace_this_with_a_very_long_secret}
  expiration-ms: 3600000
