spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:electronic_bazaar}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  application:
    name: electronic-bazaar

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:replace_this_with_a_very_long_secret}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000} # 1 hour

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
